### PR TITLE
Add command to delete firmware

### PR DESCRIPTION
**Pull request by diogomatsubara**

### CODE REVIEW

**Comment by ofaurax** [comment]
If we delete firmware, we might end up with firmware-sets referencing non-existent firmwares. We should carefully handle those cases (Should we try applying a firmware-set if one of the firmware is missing? Should we verify that no firmware-set references a given firmware before deleting it?....)

**Comment by diogomatsubara** [comment]
Not sure what you mean by partial firmware set. If you remove all firmwares from a set, the set object will still exist in ServerService but won't have a reference to any firmware, effectively being an empty set. There's no validation or constraint on the HSS side requiring a firmware set to have at least one reference to firmwares in it.

**Comment by ofaurax** [comment]
Let's get an example.

I have a base server with BMCv1 and BIOSv1.
To fix a bug, I need an update of the BIOS *and* BMC, so I create create a set with S1={BMCv2, BIOSv2}.
I can apply S1 to my base server and all is OK, I get BMCv2 and BIOSv2.

But then I find a (unrelated) bug in BMCv2, and provide BMCv3 as a fix. BMCv2 shouldn't be used because of this bug, so we delete it. S1 is now {BIOSv2}.
If I apply S1 to a new server with BMCv1 and BIOSv1, I will get a BMCv1 and BIOSv2.
I applied a *partial firmware-set*.

Possibles fixes:
* Blocking deletion of firmwares that are in firmware-set
* Blocking application of a whole firmware-set if *any* of the referenced firmware is not present

The first fix ensures we always have applicable firmware-sets (but perhaps bugged/outdated).

**Comment by diogomatsubara** [comment]
Closing since we decided that for now it's better to not delete firmware

**Pull request closed without merging**
